### ISSUE TITLE
Make option to change where the ~/.ssh/authorized_keys are written to - or allow password to be written each time

### ISSUE THREAD

**Issue by maxdignan** [mateogianolio/sshync#13]
My class' linux server prevents me from writing to any directory out of my usr/<myusername> folder. Thus sshync can't work. Is it possible to chnage where the keys are written to, or require my password every time? (Don't worry, even if I had to do this, it would still speed up my workflow).

Great usage of Node btw! Really impressive!

**Comment by mateogianolio** [comment]
Hey @maxdignan, I hadn't thought of that scenario, but it's a simple feature to add and I'll try to include it in the next patch (either today or tomorrow).

Because this script currently uses `scp` to transfer files securely, that means you'd probably have to enter your password every time a sync is performed.

And thanks for the kind words :)

**Comment by maxdignan** [comment]
Thanks man! Really appreciate it!
